version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "22:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: socket.io-client
    versions:
    - 3.0.5
  - dependency-name: "@types/async"
    versions:
    - 3.2.5
  - dependency-name: lodash
    versions:
    - 4.17.20
